# Generated by Django 6.0.2 on 2026-02-05 16:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('address_text', models.TextField()),
                ('address_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('address_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=100)),
                ('client_phone', models.CharField(max_length=20)),
                ('adresse_text', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('poids', models.CharField(blank=True, default='0 kg', max_length=50)),
                ('dimensions', models.CharField(blank=True, default='Standard', max_length=50)),
                ('est_fragile', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Livré', 'Livré'), ('Annulé', 'Annulé')], default='En attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_livraison', models.DateField(blank=True, null=True)),
                ('ordre_tournee', models.IntegerField(default=0)),
                ('livreur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Livreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_info', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('current_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_long', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='livreur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
