# Generated by Django 6.0.1 on 2026-02-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_notification_commande_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='date_collecte',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='date_en_cours',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='destination_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='destination_long',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='livreur_lat',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='livreur_long',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='livreur_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
