# Generated by Django 3.2.25 on 2026-02-10 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0004_commande_date_collecte_commande_date_en_cours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='adresse_text',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_collecte',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='date_en_cours',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='est_fragile',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='livreur_lat',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='livreur_long',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='livreur_phone',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='ordre_tournee',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='poids',
        ),
        migrations.AddField(
            model_name='commande',
            name='adresse',
            field=models.TextField(default='Adresse à définir'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='date_livraison',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='destination_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='destination_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'livreur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(default='En attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='tracking_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
