# Generated by Django 3.2.25 on 2026-02-10 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_auto_20260210_0306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='adresse',
            new_name='adresse_text',
        ),
    ]
