# Generated by Django 3.2.25 on 2026-02-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_rename_adresse_commande_adresse_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='destination_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='destination_long',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='commande',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='est_fragile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commande',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
