# Generated by Django 3.2.25 on 2026-02-10 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_alter_commande_livreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='tracking_id',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
