# Generated by Django 3.2.25 on 2026-02-10 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0009_alter_commande_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='date_livraison',
            field=models.DateField(blank=True, null=True, verbose_name='Date de Livraison Prévue'),
        ),
        migrations.AlterField(
            model_name='commande',
            name='livreur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__iexact': 'livreur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
