# Generated by Django 3.2.25 on 2026-02-10 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_auto_20260210_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('En attente', 'En attente'), ('Assignée', 'Assignée'), ('En cours', 'En cours'), ('En livraison', 'En livraison'), ('Livré', 'Livré'), ('Annulé', 'Annulé'), ('Échoué', 'Échoué'), ('Retour', 'Retour')], default='En attente', max_length=20),
        ),
    ]
